### ISSUE TITLE
Arrow shooting: scale velocity based on power

### ISSUE THREAD

**Issue by caelunshun** [feather-rs/feather#159]
Currently, arrows are shot with a constant velocity. The velocity should scale based on the bow's "pull-back" amount.

**Comment by momothereal** [comment]
I can see two ways of doing this:

* Have a data entry to keep track of the `bow_pull_start_time` in ticks (StartUse in digging packet), and calculate the difference when EndUse is sent. The advantage is it doesn't impact the tick loop.

* Have an `item_usage_time` counter that is incremented each tick when the player is in "bow pullback" state. The counter stops when EndUse is sent, and the power is calculated from the counter. The advantage is we can re-use this to keep track of food-consumption in the same way (do X after Y ticks of eating). This is what Glowstone currently does (`ItemTimedUse`).

My opinion is we could split bow and food consumption logic instead of combining both into one counter (option 1 for bow and option 2 for food only). Thoughts?

**Comment by caelunshun** [comment]
> I can see two ways of doing this:
> 
> * Have a data entry to keep track of the `bow_pull_start_time` in ticks (StartUse in digging packet), and calculate the difference when EndUse is sent. The advantage is it doesn't impact the tick loop.
> * Have an `item_usage_time` counter that is incremented each tick when the player is in "bow pullback" state. The counter stops when EndUse is sent, and the power is calculated from the counter. The advantage is we can re-use this to keep track of food-consumption in the same way (do X after Y ticks of eating). This is what Glowstone currently does (`ItemTimedUse`).
> 
> My opinion is we could split bow and food consumption logic instead of combining both into one counter (option 1 for bow and option 2 for food only). Thoughts?

Sure, that makes sense. What's the reasoning for having two separate methods for food and bows, though? I feel it would be cleaner to use the latter option for both aspects with e.g. a `TimeUsedComponent`, unless there is some reason for not doing this.

**Comment by caelunshun** [comment]
#185 will resolve this issue.

**Comment by caelunshun** [comment]
Resolved by #185.
