### ISSUE TITLE
Change crypto crates to something more secure

### ISSUE THREAD

**Issue by ThijsRay** [feather-rs/feather#164]
I noticed that the project depends on the following crypto crates
* `rsa`
* `cfb8`
* `aes`

These crates are not audited and should not be considered secure. Something else should be used instead (e.g. libsodium)

**Comment by caelunshun** [comment]
Thanks for the concerns!

We use these crates solely for [the encryption in the Minecraft protocol](https://wiki.vg/Protocol_Encryption), which requires the use of raw AES-CFB8 and RSA. Unfortunately, modern crypto libraries like `ring` and `libsodium` don't provide these ciphers, instead offering higher-level constructs. As a result, the only alternative I know of which provides the necessary functionality is OpenSSL, but that causes all sorts of problems building on Windows which are a pain to deal with.

Considering the inherent insecurities in the MC protocol encryption (notably, they use the same IV for every packet, and use no authentication tags), I wouldn't expect those crypto crates to make our encryption any less "secure," since it's already quite insecure to begin with. I might be wrong, though.

Feather previously used OpenSSL, but I gave up on it after I couldn't get it to build on CI for Windows. I'm open to switching back, though, if this problem can be solved.

**Comment by ThijsRay** [comment]
I agree. It is probably not worth the amount of effort to change the current implementation to an implementation with OpenSSL. Adding OpenSSL as a dependency can and will cause a lot of problems with the build process. This issue should be considered as low priority.

**Comment by NilsIrl** [comment]
Rustls might do the trick

**Comment by caelunshun** [comment]
> Rustls might do the trick

They don't provide raw RSA or AES-CFB8, do they? I'm afraid MC depends on a number of legacy ciphers and such which aren't provided by most modern crypto crates, so the only choices I'm aware of are OpenSSL and `rsa`/`cfb`8.

**Comment by ccgauche** [comment]
I think using OpenSSL would be a bad idea since it is a nightmare to compile. And Rustls don't provide the support for this type of encryption since they are obsolete or underspecified.
See: [https://github.com/ctz/rustls#non-features](https://github.com/ctz/rustls#non-features)
