### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by besuper** [feather-rs/feather#205]
If you drop items when your inventory is open your item going to be duplicate by 2

![duplication](https://user-images.githubusercontent.com/16976439/80652737-e3c0e680-8a78-11ea-971c-6d5773aa2a94.gif)

**Comment by caelunshun** [comment]
This would be a bug in `server/entity/object/item.rs` in the `item_collect` system. Most likely caused by our use of `unsafe` there; might be worth sacrificing a bit of performance to remove the unsafe code.

**Comment by amberkowalski** [comment]
Additionally, it appears that if you close your inventory quickly after dropping an item from your inventory, the item disappears.

**Comment by caelunshun** [comment]
I've tracked this down to what appears to be a client-side bug/abnormality. Contrary to my initial belief, this is not a bug in the `item_collect` system, nor does it have anything to do with unsafe code. Rather, what appears to happen is this:
* Under certain conditions (what exactly these are I have no idea), the creative mode client fails to send a Creative Inventory Action packet to update a slot where it picked up an item. This means that, when a user picks up an item and puts it on their cursor, the server still thinks that the original slot contains that same item.
* When the user clicks outside the window, the client sends Creative Inventory Action to drop the item. It is then duplicated, because on the server side, the item still occupies its original slot.

I'm not sure what we're doing differently from the vanilla server which causes this. We will need further investigation to find a solution.

Note that this is only a bug in creative mode; it will not happen in survival because Creative Inventory Action is not accepted.

**Comment by AnEthernetCable** [comment]
Duplication of slabs is also an issue - when breaking in survival, a single slab drops 2 slabs. Should this be a separate issue?

**Comment by caelunshun** [comment]
> Duplication of slabs is also an issue - when breaking in survival, a single slab drops 2 slabs. Should this be a separate issue?

Yes, that's a separate, unrelated issue. It arises from incomplete handling of loot table conditions.

The loot table for a slab looks e.g. like this:
```json
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "functions": [
            {
              "function": "minecraft:set_count",
              "conditions": [
                {
                  "condition": "minecraft:block_state_property",
                  "block": "minecraft:acacia_slab",
                  "properties": {
                    "type": "double"
                  }
                }
              ],
              "count": 2
            },
            {
              "function": "minecraft:explosion_decay"
            }
          ],
          "name": "minecraft:acacia_slab"
        }
      ]
    }
  ]
}
```

The item count should only be set to 2 when the slab has the `double` type, but conditions aren't yet properly handled by Feather's loot table implementation. I'll open an issue.

**Comment by amberkowalski** [comment]
Closed - Outdated
