### ISSUE TITLE
Feature Suggestion: Crossplay with Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by SmushyTaco** [feather-rs/feather#235]
If you watch this video: https://www.youtube.com/watch?v=gIQm-XxKHQo

and go to the GitHub here: https://github.com/DragonetMC/DragonProxy/

You'll see that it's possible to have crossplay with Java Edition and Bedrock Edition players and having this here would be amazing (Obviously you guys have priorities with getting it production ready for just Java Edition so far but I thought you guys would also like to keep this in mind)!

Edit: Useful wiki: https://minecraft.gamepedia.com/Bedrock_Edition_server_software

**Comment by TypicalDarkness** [comment]
Maybe I'm misunderstanding this, but since DragnonMC (and now Geyser) are just proxies, shouldn't it be agnostic to the server implementation and this just work just out of the box?

**Comment by pofdzm** [comment]
It would be better to make this as a plugin if possible instead of directly implementing it + not everything is perfectly same and some client side and server site physics contradicts so you also need some modified client to run exactly like java edition. They are just little physics but can matter unless you are just a small minigame server with much details, tho idk maybe there is different pvp mechanics can be either, didn't researched on it.
