### ISSUE TITLE
Feature Suggestion: Paper Plugin Compatibility Layer

### ISSUE THREAD

**Issue by SmushyTaco** [feather-rs/feather#236]

**Comment by hktr92** [comment]
There are two crates that can call Java code from Rust:
- first one is called [j4rust](https://github.com/astonbitecode/j4rs#Basics)
- second one is called [jni-rs](https://github.com/jni-rs/jni-rs)

I don't know for sure which one could fit better the task. `j4rs` feels easier and more documented rather than `jni-rs`, and the latter seems more for the rust-to-java. They also recommended [GraalVM](https://www.graalvm.org/), which I don't know if there's any gain from using it inside this project.

And, if a reference is needed, [Deno](https://github.com/denoland/deno) is a TypeScript / JavaScript runtime written in Rust. They used / created `rusty_v8` crate to have bindings for V8 JavaScript engine in Rust. They did a pretty great job doing this kind of task. I'm optimist about doing this task, tbh.
