### ISSUE TITLE
Gamerules abstraction

### ISSUE THREAD

**Issue by onbjerg** [feather-rs/feather#251]
We should create an abstraction for gamerules that should be

- available to all event handlers
- serializable so we can persist the game rules
- configurable by commands (i.e. the `/gamerule` command)

I think we should do this soon-ish as some of the gamerules might have implications for multiple parts of the code base and we might have a lot of after-the-fact work to do if we don't.

[Complete list of game rules](https://minecraft.gamepedia.com/Commands/gamerule#Arguments)

**Comment by Defman** [comment]
Gamerule should be an enum and live either on `Shared` or `Game` object.
```rust
enum GameRule {
  RandomTickSpeed(u32),
  DoMobLoot(bool),
  ...
} 

struct Game {
    game_rules: BTreeSet<GameRule>,
}
```

GameRule should implement `Default`, we could also use `Box<[GameRule; N]>` where `N` is the number of gamerules and have some function that maps an `enum` to its "id".

**Comment by PauMAVA** [comment]
Hey! 

If this is still open I understand that it hasn't been implemented yet. I can try to implement this if you want. 

I am quite new to rust (only made a couple of projects) but I am looking forward to contributing to this project since I have a lot of interest and experience with Minecraft development and I believe a Rust based server would perform a lot better than a Java based one. 

Do you have any contribution guidelines like code styling or others?

Another question, shouldn't this be implemented on the new `libcraft` [repo](https://github.com/feather-rs/libcraft/)?

**Comment by Defman** [comment]
There exist an old pr that implements game rules, however it never got merged do to refactoring in the 1.16 branch and the addition of libcraft. You are more than welcome to implement it, you can get some ideas from the old pr. Though skip the macro rules and just manually implement Default.

**Comment by PauMAVA** [comment]
Okay, thanks! I will try to find the PR and implement it. 

Should I implement it here directly or in the `libcraft` repo?

**Comment by Defman** [comment]
I remembered wrong, the pr got merged but that does matter much.  #252

Implement it in `libcraft` and instead of doing a macro like I did just manually implement `Default`.

**Comment by PauMAVA** [comment]
Okay. I will open an issue on `libcraft` and implement it there without the macros.

**Comment by PauMAVA** [comment]
Should we leave this issue open for when we implement the `libcraft` types into `feather`?
