### ISSUE TITLE
Feature Suggestion: Feather Modding API

### ISSUE THREAD

**Issue by SmushyTaco** [feather-rs/feather#258]
This would be a modding API (Like ModLoader, Forge, Fabric, LiteLoader, Rift, etc) but would use Rust and would be built to play well with the Feather server software so people could make modded servers using this tech.

**Comment by caelunshun** [comment]
Mainly this depends on:

* A fully featured client implementation in Rust (based on Feather's internals), since we can't run Rust plugins in vanilla.
* Finishing the plugin API. I imagine the modding API could just be an extension to the existing plugin API, since they share most of the API surface.

Because of the former point, it's probably something for the distant future, as there's only so much time, and currently the focus is making the server in a playable state.

**Comment by PaulTheNeko** [comment]
I'm not a contributor, but from what I've seen the plugin system would most likely be based on wasm.

This means we can avoid rewriting the client and instead simply make a mod that would load wasm mods into the game.

Ofc this means copying the entire modding API into the client, which is a ton of work still.
So I agree it has to be put off into the distant future (if implemented at all).
