### ISSUE TITLE
Client gets unexpectedly disconnected when dropping a diamond with inventory open in survival

### ISSUE THREAD

**Issue by PonasKovas** [feather-rs/feather#297]
```
2020-08-15 23:20:11,487 INFO  [feather_server_types::game] player disconnected: error handling Click Window packet: invalid protocol index 18446744073709550617
```

**Comment by toiglak** [comment]
Looks like function `handle_single_click()` don't have implemented clicking outside the inventory window. The bug comes from conversion to `usize` after which slot number `-999` ([reserved for clicking outside the window](https://wiki.vg/Inventory)) becomes too big to access valid inventory slot and returns an error. 
https://github.com/feather-rs/feather/blob/5b27cefdf419ef1788680f268f2d0c499f521d3f/server/player/src/packet_handlers/inventory.rs#L338

I think I can fix this. I will take a reference from `handle_creative_inventory_action()`.

**Comment by Deliquescence** [comment]
Having also looked into this a little, I think the `Mode` `TryFrom` impl should possibly be updated. I think the `handle_item_drop` fn (which is marked as TODO) is intended to handle this, so that should probably be called instead of parsing mode 4 as unhandled (see below).

https://github.com/feather-rs/feather/blob/5b27cefdf419ef1788680f268f2d0c499f521d3f/server/player/src/packet_handlers/inventory.rs#L202-L204

**Comment by Deliquescence** [comment]
Actually it might not relate to mode 4 specifically because that is only for [when no item is held](https://wiki.vg/Protocol#Click_Window)(?) Sorry if that was a red herring; I was just trying to incorporate the `handle_item_drop` fn in order to avoid making `handle_single_click` more complicated than it had to be.

**Comment by toiglak** [comment]
Oh yes, I actually missed `handle_item_drop` function. In that case, I think there should be added a simple check inside `try_from` fn for `mode 0` (see below) that if `slot==-999` it will return `Mode::ItemDrop` with `full_stack` based on `MouseButton`.
https://github.com/feather-rs/feather/blob/5b27cefdf419ef1788680f268f2d0c499f521d3f/server/player/src/packet_handlers/inventory.rs#L180-L186
