### ISSUE TITLE
Very fast block breaks (e.g. via golden tools) are not detected

### ISSUE THREAD

**Issue by Deliquescence** [feather-rs/feather#300]
I initially discovered this by digging snow with a golden shovel, and also reproduced by digging netherrack with a golden pickaxe. If enchantments or haste potion were implemented, they could also be used to trigger the issue.

When a block break is very fast but not instant (I believe 0.05 seconds or less based on https://minecraft.gamepedia.com/Breaking#Blocks_by_hardness), then the block will not be broken when the client thinks it is, as revealed by relogging.

I think the issue is that the vanilla client just doesn't bother to send a finished digging packet for these cases. My current planned fix I will be working on is to refactor `advance_dig_progress` to handle checking if the block should be broken instead of relying on the finished digging packet. This has the added benefit of not trusting the client to determine when the block breaks.

**Comment by KnoxZZ** [comment]
I think this could be an issue with the `handle_started_digging` instead of `advance_dig_process` since according to [this wiki page](https://minecraft.gamepedia.com/Breaking#Instant_breaking) players can instantly break blocks if one of 2 requirements is fullfilled.
1.  player is in creative gamemode
2. The "damage" player does to the block per tick is higher than the blocks hardness times 30

https://github.com/feather-rs/feather/blob/9539a21c9c0fbe681ec1e8851519280438dd583f/server/player/src/packet_handlers/digging.rs#L123-L130
In the current `handle_started_digging` implementation the second requirement is not checked. Instead it checks if hardness is 0.

This could also explain why the client doesn't bother to send any finished digging packet.

**Comment by KnoxZZ** [comment]
Another problem with mining speed handling is that the https://github.com/feather-rs/feather/blob/9539a21c9c0fbe681ec1e8851519280438dd583f/definitions/src/generated/tool.rs#L1-L178
file is lacking most of the `best_tool` and `best_tool_required` data.

I'm unfamiliar with autogenerated rust code, so could someone help me and generate more comprehensive `best_tool` and `best_tool_required` functions. Or give me instructions on how to do it myself.

**Comment by Deliquescence** [comment]
You can look at [my branch](https://github.com/Deliquescence/feather/tree/fast-breaks) that I was working on. If I recall correctly, it works ok but I never implemented the check for being in water and I didn't like the implementation of `finish_fast_diggings` because of the `Collect`.
I haven't been motivated to polish it off (partially because of the whole 1.16 branch thing) so feel free to use it as you see fit (or don't, up to you).

To help answer your question about the best tool generation, you can check the changes I made to `definitions/data/tool.ron` to add snow and netherrack for testing, but I don't have any advice on a more automated method.

Also, I wasn't aware of the "blocks hardness times 30" threshold you mentioned in your first comment so maybe whatever I was doing could be improved using that information.
